[gravity]
domain = "gravity"
host = "0.0.0.0:32803"

[subscriber]
subscriber_id = "oracle_transmitter"
subscriber_name = "Oracle Transmitter"
state_store = "./statestore"
worker_count = 4
verbose = true
pipeline_start = 0
pipeline_end = -1

[initial_load]
enabled = true
omitted_count = 100000



[rules]
subscription = "./settings/subscriptions.json"

[database]
host = "192.168.1.111"
port = 1521
username = "gravity"
password = "gravity"
# Only one of service_name or sid can be used
service_name = "orcl"
sid = ""
# param = "PROTOCAL=TCP&as=sysdba"
param = ""
