[service]
port = 44143

[database]
host = "localhost"
port = 31222
username = "sys"
password = "Oradoc_db1"
# Only one of service_name or sid can be used
service_name = "ORCL.local"
sid = ""
param = "PROTOCAL=TCP&as=sysdba"
